### ISSUE TITLE
Fix the guide to use the new Gretty plugin

### ISSUE THREAD

**Issue by pledbrook** [gradle-guides/building-java-web-applications#17]
Also check whether there are any tests to ensure that the guide is accurate when new versions of Gradle come out.

**Comment by pledbrook** [comment]
See [this StackOverflow question](https://stackoverflow.com/questions/51127367/gradle-building-java-web-applications) for a description of the current issue.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #239](https://github.com/gradle/guides/issues/239) via [**ZenHub**](https://www.zenhub.com/)
