### ISSUE TITLE
Current guide is not working with Java 9 on my system

### ISSUE THREAD

**Issue by miken700** [gradle-guides/building-java-web-applications#19]
With using Java 9, I had added this to `build.gradle` to get the appRun task to execute with out errors on the response.jsp page,

```
sourceCompatibility = 1.8
targetCompatibility = 1.8
```

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #256](https://github.com/gradle/guides/issues/256) via [**ZenHub**](https://www.zenhub.com/)
