### ISSUE TITLE
The appRun task fails on JSP compile

### ISSUE THREAD

**Issue by rnikander** [gradle-guides/building-java-web-applications#21]
I get this when I do `gradle appRun` and post to the servlet. I've tried it on Java 10 and 12 on macOS. Gradle version 5.4.

    May 03, 2019 1:13:15 PM org.apache.jasper.compiler.Compiler generateClass
    SEVERE: Error compiling file: /Users/[...]/hiweb/build/serverBaseDir_jetty9/webapps-exploded/hiweb/jsp/org/apache/jsp/response_jsp.java
    13:13:15 WARN  
    org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP
    
    PWC6199: Generated servlet error:
    source value 7 is obsolete and will be removed in a future release
    
    PWC6199: Generated servlet error:
    target value 7 is obsolete and will be removed in a future release
    
    PWC6199: Generated servlet error:
    To suppress warnings about obsolete options, use -Xlint:-options.
    
    PWC6199: Generated servlet error:
    package org.apache.jasper.runtime does not exist
    
    PWC6199: Generated servlet error:
    package org.apache.jasper.runtime does not exist
    
    PWC6199: Generated servlet error:
    cannot find symbol
      symbol:   class JspFactory
      location: class org.apache.jsp.response_jsp
    
    PWC6199: Generated servlet error:
    package org.glassfish.jsp.api does not exist
    
    PWC6199: Generated servlet error:
    cannot find symbol
      symbol:   class HttpServletRequest
      location: class org.apache.jsp.response_jsp
    [... more ...]

**Comment by FlorianParty** [comment]
You can check the answer to this Stackoverflow question: [https://stackoverflow.com/questions/57409285/building-a-java-web-app-as-in-gradle-guide-throws-many-errors-opening-jsp-file/]

I hope it will help you

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #274](https://github.com/gradle/guides/issues/274) via [**ZenHub**](https://www.zenhub.com/)
