### ISSUE TITLE
First `build.gradle` applies both `war` and `jar` plugins

### ISSUE THREAD

**Issue by Dispader** [gradle-guides/building-java-web-applications#7]
In [the first sample `build.gradle`](https://github.com/gradle-guides/building-java-web-applications/blob/5f5fa3aae94e4d4fc11dd7fac872117d05f5610d/samples/code/webdemo/build.gradle#L3), it looks like we specify both the `java` and `war` plugins.

I thought that the `war` plugin implied the `java` plugin transitively.  Iffn that's right, d'you think we should get rid of the `java` plugin line here?

**Comment by pledbrook** [comment]
The submitted fix was merged.
